feat: l1ToL2MessageNonce
keep-starknet-strange/beerus pull request #119
Opened 2022-12-15 13:24 UTC by ClementWalter

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Feature not implemented

Resolves #98 

# What is the new behavior?

Implemented in core, cli & api

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

I was not sure about the key of the response JSON in the API (used `result`, should it be `nonce`?)

2022-12-15 13:38 UTC, LucasLvy requested changes

2022-12-15 13:38 UTC, LucasLvy commented on beerus_cli/src/starknet/mod.rs
> +/// * `Result<()>` - The result of the query.
```suggestion
/// * `Result<CommandResponse>` - The result of the query.
```

2022-12-16 09:30 UTC, abdelhamidbakhta requested changes
Please address comments

2022-12-16 09:30 UTC, abdelhamidbakhta commented on beerus_cli/tests/cli.rs
> +    #[tokio::test]
Please add error cases

2022-12-16 09:30 UTC, abdelhamidbakhta commented on beerus_cli/src/model.rs
> +    /// The nonce of the L1 to L2 message bridge
Comment should be above the line

2022-12-16 09:30 UTC, abdelhamidbakhta commented on beerus_core/tests/beerus.rs
> +    async fn given_normal_conditions_when_call_get_l1_to_l2_message_nonce_then_should_return_ok() {
Please add error cases

2022-12-16 09:30 UTC, abdelhamidbakhta commented on beerus_rest_api/tests/api.rs
> +    #[tokio::test]
Please add error cases

2022-12-16 10:40 UTC, ClementWalter commented
I'm doing the error cases now; I left them apart first because I was not sure that these my ongoing work were correctly written, so I wanted a first approval to avoid to much rework, thxs!

2022-12-16 11:33 UTC, abdelhamidbakhta commented
> I'm doing the error cases now; I left them apart first because I was not sure that these my ongoing work were correctly written, so I wanted a first approval to avoid to much rework, thxs!

Makes sense, thanks

2022-12-19 17:34 UTC, abdelhamidbakhta approved these changes
lgtm
please resolve conflicts

2022-12-20 08:03 UTC, abdelhamidbakhta approved these changes
lgtm

2022-12-20 09:26 UTC, abdelhamidbakhta approved these changes
lgtm

2022-12-20 09:26 UTC, merged