Implemented starknet_getStorageAt
keep-starknet-strange/beerus pull request #369
Opened 2023-04-08 12:40 UTC by dpinones

Implemented starknet_getStorageAt

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #362 

# What is the new behavior?

-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

2023-04-12 09:18 UTC, phklive commented
Hey man how is it going? Let's close the rpc asap.

2023-04-12 18:25 UTC, dpinones commented
Hey @phklive, I added the changes that are in the PR #371 to be able to implement the RPC endpoint without Helios errors. The RPC endpoint is functioning properly. However, I am getting an error in the "[check](https://github.com/keep-starknet-strange/beerus/actions/runs/4681351376/jobs/8294010849?pr=369)" job. To merge this PR, the PR #371  where they update the Helios version must be merged first and all jobs must be executed without issues.

2023-04-13 16:27 UTC, phklive requested changes
Only thing would be BlockId as params rest lgtm

2023-04-13 16:27 UTC, phklive commented on crates/beerus-rpc/src/api.rs
> +        contract_address: String,
If I am not mistaken starknet_getStorageAt also takes a BlockId:
<img width="1259" alt="SCR-20230413-qbqi" src="https://user-images.githubusercontent.com/42912740/231823589-257f9730-07e9-4cac-b719-f7c174e56e79.png">

As seen here.

2023-04-13 17:48 UTC, phklive commented on crates/beerus-rpc/src/api.rs
> +        contract_address: String,
I agree i will create an issue and take care of the get_nonce now.

2023-04-13 18:04 UTC, phklive commented on crates/beerus-rpc/src/api.rs
> +        contract_address: String,
Will create issues for adding blockId as a parameter after merging BlockId PR: https://github.com/keep-starknet-strange/beerus/pull/391

Well done.

2023-04-13 22:01 UTC, phklive commented
lgmt

2023-04-13 22:07 UTC, phklive commented
Let's build 🚀

2023-04-13 22:07 UTC, merged