Fix bug: the starknet_getEvents rpc method is failing bug
keep-starknet-strange/beerus pull request #537
Opened 2023-08-13 19:49 UTC by tonypony220

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: N/A

# What is the new behavior?

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

# Other information

2023-08-14 16:27 UTC, Aragar199 requested changes
Can you try running `from:` and `to:` blocks as `latest` to see if we can not hard code the block values? @tonypony220

2023-08-15 21:32 UTC, drspacemn approved these changes
do you plan on implementing Alex's suggestion?

2023-08-15 23:28 UTC, tonypony220 commented
> Can you try running `from:` and `to:` blocks as `latest` to see if we can not hard code the block values? @tonypony220

Yes, it works. And without `to block` too.
@Aragar199

2023-08-16 04:10 UTC, Aragar199 approved these changes

2023-08-16 04:13 UTC, merged